# Created with https://github.com/dart-lang/mono_repo
language: dart

jobs:
  include:
    - stage: smoke_test
      env: PKG="mono_repo" COMMANDS="dartfmt dartanalyzer"
      script: ./tool/travis.sh
      dart: dev
    - stage: unit_test
      env: PKG="mono_repo" COMMANDS="test_0"
      script: ./tool/travis.sh
      dart: dev
    - stage: unit_test
      env: PKG="mono_repo" COMMANDS="test_1"
      script: ./tool/travis.sh
      dart: dev

stages:
  - smoke_test
  - unit_test

# Only building master means that we don't run two builds for each pull request.
branches:
  only: [master]

cache:
  directories:
    - $HOME/.pub-cache
