# Created with package:mono_repo v3.0.0-dev
language: dart

jobs:
  include:
    - stage: smoke_test
      name: "SDK: 2.7.0; PKG: mono_repo; TASKS: `dartanalyzer --fatal-warnings .`"
      dart: "2.7.0"
      os: linux
      env: PKGS="mono_repo"
      script: tool/travis.sh dartanalyzer_1
    - stage: smoke_test
      name: "SDK: dev; PKG: mono_repo; TASKS: [`dartfmt -n --set-exit-if-changed .`, `dartanalyzer --fatal-infos --fatal-warnings .`, `cd ../ && dart mono_repo/bin/mono_repo.dart travis --validate`]"
      dart: dev
      os: linux
      env: PKGS="mono_repo"
      script: tool/travis.sh dartfmt dartanalyzer_0 command_0
    - stage: smoke_test
      name: "SDK: dev; PKG: test_pkg; TASKS: [`dartfmt -n --set-exit-if-changed .`, `dartanalyzer --fatal-infos --fatal-warnings .`]"
      dart: dev
      os: linux
      env: PKGS="test_pkg"
      script: tool/travis.sh dartfmt dartanalyzer_0
    - stage: unit_test
      name: "SDK: 2.7.0; PKG: mono_repo; TASKS: `pub run test -P presubmit`"
      dart: "2.7.0"
      os: linux
      env: PKGS="mono_repo"
      script: tool/travis.sh command_1
    - stage: unit_test
      name: "SDK: 2.7.0; PKG: mono_repo; TASKS: `pub run test -P presubmit`"
      dart: "2.7.0"
      os: windows
      env: PKGS="mono_repo"
      script: tool/travis.sh command_1
    - stage: unit_test
      name: "SDK: dev; PKG: mono_repo; TASKS: `pub run test -P presubmit`"
      dart: dev
      os: linux
      env: PKGS="mono_repo"
      script: tool/travis.sh command_1
    - stage: unit_test
      name: "SDK: dev; PKG: mono_repo; TASKS: `pub run test -P presubmit`"
      dart: dev
      os: windows
      env: PKGS="mono_repo"
      script: tool/travis.sh command_1
    - stage: unit_test
      name: "SDK: dev; PKG: test_pkg; TASKS: `pub run test`"
      dart: dev
      os: linux
      env: PKGS="test_pkg"
      script: tool/travis.sh test

stages:
  - smoke_test
  - unit_test

# Only building master means that we don't run two builds for each pull request.
branches:
  only:
    - master

cache:
  directories:
    - "$HOME/.pub-cache"
    - mono_repo/.dart_tool/build
