# Created with package:mono_repo v1.2.3-dev
language: dart

jobs:
  include:
    - stage: smoke_test
      name: "SDK: dev - DIR: mono_repo - TASKS: [dartfmt -n --set-exit-if-changed ., dartanalyzer --fatal-infos --fatal-warnings .]"
      script: ./tool/travis.sh dartfmt dartanalyzer_0
      env: PKG="mono_repo"
      dart: dev
    - stage: smoke_test
      name: "SDK: 2.1.0 - DIR: mono_repo - TASKS: [dartfmt -n --set-exit-if-changed ., dartanalyzer --fatal-warnings .]"
      script: ./tool/travis.sh dartfmt dartanalyzer_1
      env: PKG="mono_repo"
      dart: "2.1.0"
    - stage: build
      name: "SDK: 2.1.0 - DIR: mono_repo - TASKS: pub run build_runner build test --delete-conflicting-outputs"
      script: ./tool/travis.sh command_0
      env: PKG="mono_repo"
      dart: "2.1.0"
    - stage: build
      name: "SDK: dev - DIR: mono_repo - TASKS: pub run build_runner build test --delete-conflicting-outputs"
      script: ./tool/travis.sh command_0
      env: PKG="mono_repo"
      dart: dev
    - stage: unit_test
      name: "SDK: 2.1.0 - DIR: mono_repo - TASKS: [pub run build_runner test -- -x presubmit-only, pub run build_runner test -- --run-skipped -t presubmit-only]"
      script: ./tool/travis.sh command_1 command_2
      env: PKG="mono_repo"
      dart: "2.1.0"
    - stage: unit_test
      name: "SDK: dev - DIR: mono_repo - TASKS: [pub run build_runner test -- -x presubmit-only, pub run build_runner test -- --run-skipped -t presubmit-only]"
      script: ./tool/travis.sh command_1 command_2
      env: PKG="mono_repo"
      dart: dev

stages:
  - smoke_test
  - build
  - unit_test

# Only building master means that we don't run two builds for each pull request.
branches:
  only:
    - master

cache:
  directories:
    - "$HOME/.pub-cache"
    - mono_repo/.dart_tool/build
