# Created with https://github.com/dart-lang/mono_repo
language: dart

jobs:
  include:
    - stage: smoke_test
      script: ./tool/travis.sh dartfmt
      env: PKG="mono_repo"
    - stage: smoke_test
      script: ./tool/travis.sh dartanalyzer
      env: PKG="mono_repo"
    - stage: unit_test
      script: ./tool/travis.sh test
      env: PKG="mono_repo"
    - stage: unit_test
      script: ./tool/travis.sh command_0
      env: PKG="mono_repo"
    - stage: unit_test
      script: ./tool/travis.sh command_1
      env: PKG="mono_repo"

stages:
  - smoke_test
  - unit_test


# Only building master means that we don't run two builds for each pull request.
branches:
  only: [master]

cache:
 directories:
   - $HOME/.pub-cache
