# See https://github.com/google/mono_repo.dart for details
dart:
- 2.6.0
- dev

stages:
- smoke_test:
  - group:
    - dartfmt
    - dartanalyzer: --fatal-infos --fatal-warnings .
    dart: [dev]
  - group:
    - dartanalyzer: --fatal-warnings .
    dart: [2.6.0]
- unit_test:
  - test:
    os:
      - linux
      - windows
