# See https://github.com/google/mono_repo.dart for details
dart:
- dev

stages:
- smoke_test:
  - group:
    - dartfmt
    - dartanalyzer: --fatal-infos --fatal-warnings .
    dart: [dev]
- unit_test:
  - test:
    os:
      - linux
