# See https://github.com/dart-lang/mono_repo for details
dart:
  - dev

stages:
  - smoke_test:
    - group:
        - dartfmt
        - dartanalyzer: --fatal-infos --fatal-warnings .
  - unit_test:
    - test: -x presubmit-only
    - test: --run-skipped -t presubmit-only
