# See https://github.com/dart-lang/mono_repo for details
dart:
  - dev

stages:
  - smoke_test:
    - group:
        - dartfmt
        - dartanalyzer: --fatal-infos --fatal-warnings .
  - build:
    - command: pub run build_runner build test
  - unit_test:
    - group:
      - test: -x presubmit-only
      - test: --run-skipped -t presubmit-only
