language: dart
sudo: false
dart:
  - dev

dart_task:
  - dartfmt
  - dartanalyzer: --fatal-infos --fatal-warnings .
  - test

# Only building master means that we don't run two builds for each pull request.
branches:
  only: [master]

cache:
 directories:
   - $HOME/.pub-cache
