# See https://github.com/dart-lang/mono_repo for details
dart:
- 2.2.0
- dev

stages:
- smoke_test:
  - group:
    - dartfmt
    - dartanalyzer: --fatal-infos --fatal-warnings .
    dart: [dev]
  - group:
    - dartanalyzer: --fatal-warnings .
    dart: [2.2.0]
- build:
  - command: pub run build_runner build test --delete-conflicting-outputs
- unit_test:
  - group:
    - command: pub run build_runner test -- -x presubmit-only
    - command: pub run build_runner test -- --run-skipped -t presubmit-only

cache:
  directories:
  - .dart_tool/build
