# See https://github.com/dart-lang/mono_repo for details
dart:
  - stable
  - dev

stages:
  - smoke_test:
    - description: "dartfmt && dartanalyzer"
      group:
        - command: dartfmt --fix -n --set-exit-if-changed .
        - dartanalyzer: --fatal-infos --fatal-warnings .
  - build:
    - command: pub run build_runner build test --delete-conflicting-outputs
  - unit_test:
    - group:
      - command: pub run build_runner test -- -x presubmit-only
      - command: pub run build_runner test -- --run-skipped -t presubmit-only

cache:
  directories:
    - .dart_tool/build
