# See https://github.com/google/mono_repo.dart for details

stages:
- smoke_test:
  - group:
    # https://github.com/google/mono_repo.dart/issues/199
    - command: cd ../ && dart mono_repo/bin/mono_repo.dart travis --validate
    name: mono_repo self validate
    dart: dev
  - group:
    - dartfmt
    - dartanalyzer: --fatal-infos --fatal-warnings .
    dart: dev
  - dartanalyzer: --fatal-warnings .
    dart: 2.7.0
- unit_test:
  - command: pub run test -P presubmit
    os:
      - linux
      - windows
    dart: [2.7.0, dev]

cache:
  directories:
  - .dart_tool/build
