# See https://github.com/google/mono_repo.dart for details

stages:
- smoke_test:
  # https://github.com/google/mono_repo.dart/issues/199
  - command: cd ../ && dart mono_repo/bin/mono_repo.dart generate --validate
    dart: dev
  - group:
    - dartfmt
    - dartanalyzer: --fatal-infos .
    dart: dev
  - dartanalyzer:
    dart: 2.7.0
- unit_test:
  - test: -x yaml -P presubmit --test-randomize-ordering-seed=random
    os:
    - linux
    - windows
    dart: [2.7.0, dev]
  - test: -t yaml --test-randomize-ordering-seed=random
    os:
    - linux
    dart: [2.7.0, dev]

cache:
  directories:
  - .dart_tool/build
