# See https://github.com/google/mono_repo.dart for details
dart:
- 2.7.0
- dev

stages:
- smoke_test:
  - group:
    - dartfmt
    - dartanalyzer: --fatal-infos --fatal-warnings .
    # A bit weird, this should really be a global task but we don't have those.
    - command: cd ../ && dart mono_repo/bin/mono_repo.dart travis --validate
    dart: [dev]
  - group:
    - dartanalyzer: --fatal-warnings .
    dart: [2.7.0]
- build:
  - command: pub run build_runner build test --delete-conflicting-outputs
    os:
      - linux
      - windows
- unit_test:
  - command: pub run build_runner test --delete-conflicting-outputs -- -P presubmit
    os:
      - linux
      - windows

cache:
  directories:
  - .dart_tool/build
