# Created with package:mono_repo v3.1.0
name: Dart CI
on:
  push:
    branches:
      - main
      - master
  pull_request:
  schedule:
    - cron: "0 0 * * 0"
defaults:
  run:
    shell: bash
env:
  PUB_ENVIRONMENT: bot.github

jobs:
  job_001:
    runs-on: ubuntu-latest
    steps:
      - run: export
  job_007:
    runs-on: ubuntu-latest
    steps:
      - run: not_a_command
  job_009:
    name: "so we done?"
    runs-on: ubuntu-latest
    if: always()
    needs:
      - job_001
      - job_007
    steps:
      - run: export
      - run: ls $GITHUB_PATH
        continue-on-error: true
      - run: ls -l /home/runner/work/_temp/_github_workflow
        continue-on-error: true
      - run: pushd /home/runner/work/_temp/ && ls -l
        continue-on-error: true
      - run: pushd /home/runner/work/_temp/ && for f in `ls`; do echo "Processing $f file.."; cat $f; done
        continue-on-error: true
      - run: pushd /home/runner/work/_temp/_runner_file_commands/ && for f in `ls`; do echo "Processing $f file.."; cat $f; done
        continue-on-error: true
