# Created with package:mono_repo v3.1.0-beta.5-dev
name: Dart CI
on:
  push:
    branches:
      - main
      - master
  pull_request:
  schedule:
    - cron: "0 0 * * 0"
defaults:
  run:
    shell: bash
env:
  PUB_ENVIRONMENT: bot.github

jobs:
  job_005:
    name: "OS: windows; SDK: 2.7.0; PKG: mono_repo; TASKS: `pub run test -P presubmit --test-randomize-ordering-seed=random`"
    runs-on: windows-latest
    steps:
      - run: "ls %LOCALAPPDATA%\Pub\Cache\hosted"
